version: '3.3'

services:
  db:
    image: "postgres:11.1-alpine"
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    networks:
      - ticket-service
    volumes:
      - ticket_db:/var/lib/postgresql/data

  backend:
    build: backend/
    restart: on-failure
    volumes:
      - ./backend:/backend
      - ./backend/wait-for-postgres.sh:/backend/wait-for-postgres.sh
    ports:
      - "5000:5000"
    env_file: .env
    command: ["./wait-for-postgres.sh", "db", "entrypoint-dev.sh"]
    networks:
      - ticket-service
    depends_on:
      - db

  frontend:
    build: frontend/
    restart: on-failure
    env_file:
      - .env
    command: yarn start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/build
    networks:
      - ticket-service
    depends_on:
      - backend

  nginx:
    image: "nginx:1.15.7-alpine"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - ticket-service
    depends_on:
      - backend
      - frontend

networks:
  ticket-service:
    driver: bridge

volumes:
  ticket_db:
