version: '3.7'

services:
  db:
    image: "postgres:11.1-alpine"
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    networks:
      - ticket-service
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build: backend/
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file: .env
    command: sh -c "python3 manage.py db migrate && python3 manage.py db upgrade && gunicorn -w 2 -b 0.0.0.0:8000 app:app --reload"
    networks:
      - ticket-service
    depends_on:
      - db

  frontend:
    build: frontend/
    restart: on-failure
    env_file:
      - .env
    command: yarn start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/build
    networks:
      - ticket-service
    depends_on:
      - backend

  nginx:
    image: "nginx:1.15.7-alpine"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - ticket-service
    depends_on:
      - backend
      - frontend

networks:
  ticket-service:
    driver: bridge
