export const CLEAR_ERROR    = 'CLEAR_ERROR'
export const CLEAR_NOTI     = 'CLEAR_NOTI'

export const LOGIN_SUBMIT   = 'LOGIN_SUBMIT'
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS'
export const LOGIN_FAIL     = 'LOGIN_FAIL'
export const LOGIN_FAIL_3   = 'LOGIN_FAIL_3'

export const SIGNUP_SUBMIT  = 'SIGNUP_SUBMIT'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL    = 'SIGNUP_FAIL'

export const RESET_PASSWORD_SUBMIT  = 'RESET_PASSWORD_SUBMIT'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL    = 'RESET_PASSWORD_FAIL'

export const CHANGE_PASSWORD_SUBMIT  = 'CHANGE_PASSWORD_SUBMIT'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL    = 'CHANGE_PASSWORD_FAIL'

export const NOTI_TYPE_SUCCESS  = 'SUCCESS'
export const NOTI_TYPE_FAIL     = 'FAIL'
