"""empty message

Revision ID: 86db1a9250e0
Revises: db9b2b742a8d
Create Date: 2019-01-08 02:38:46.532735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86db1a9250e0'
down_revision = 'db9b2b742a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'action', ['id'])
    op.create_unique_constraint(None, 'history_pass_change', ['id'])
    op.create_unique_constraint(None, 'history_wrong_pass', ['id'])
    op.create_unique_constraint(None, 'logging', ['id'])
    op.create_unique_constraint(None, 'signup_request', ['id'])
    op.create_unique_constraint(None, 'user_token', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='unique')
    op.drop_constraint(None, 'signup_request', type_='unique')
    op.drop_constraint(None, 'logging', type_='unique')
    op.drop_constraint(None, 'history_wrong_pass', type_='unique')
    op.drop_constraint(None, 'history_pass_change', type_='unique')
    op.drop_constraint(None, 'action', type_='unique')
    # ### end Alembic commands ###
