"""empty message

Revision ID: a432ef9fb63a
Revises: 
Create Date: 2019-01-02 14:51:58.497671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a432ef9fb63a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'action', ['id'])
    op.create_unique_constraint(None, 'history_pass_change', ['id'])
    op.create_unique_constraint(None, 'history_wrong_pass', ['id'])
    op.create_unique_constraint(None, 'logging', ['id'])
    op.add_column('signup_request', sa.Column('user_token_confirm', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'signup_request', ['id'])
    op.create_unique_constraint(None, 'user_token', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='unique')
    op.drop_constraint(None, 'signup_request', type_='unique')
    op.drop_column('signup_request', 'user_token_confirm')
    op.drop_constraint(None, 'logging', type_='unique')
    op.drop_constraint(None, 'history_wrong_pass', type_='unique')
    op.drop_constraint(None, 'history_pass_change', type_='unique')
    op.drop_constraint(None, 'action', type_='unique')
    # ### end Alembic commands ###
