"""empty message

Revision ID: cf4a0f159ef4
Revises: 210a101a567b
Create Date: 2018-12-27 16:11:30.070070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4a0f159ef4'
down_revision = '210a101a567b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'action', ['id'])
    op.create_unique_constraint(None, 'history_pass_change', ['id'])
    op.create_unique_constraint(None, 'history_wrong_pass', ['id'])
    op.create_unique_constraint(None, 'logging', ['id'])
    op.create_unique_constraint(None, 'signup_request', ['id'])
    op.create_unique_constraint(None, 'user_token', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='unique')
    op.drop_constraint(None, 'signup_request', type_='unique')
    op.drop_constraint(None, 'logging', type_='unique')
    op.drop_constraint(None, 'history_wrong_pass', type_='unique')
    op.drop_constraint(None, 'history_pass_change', type_='unique')
    op.drop_constraint(None, 'action', type_='unique')
    # ### end Alembic commands ###
