"""empty message

Revision ID: dbb79079508d
Revises: cf4a0f159ef4
Create Date: 2019-01-02 14:45:56.186861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb79079508d'
down_revision = 'cf4a0f159ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_request', sa.Column('access_token_config', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup_request', 'access_token_config')
    # ### end Alembic commands ###
